name: PR Tests

on:
  push:
    branches-ignore:
      - main

jobs:
  pr-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          python-version: "3.12"

      - name: Install Python dependencies
        run: uv pip install -r requirements.txt

      - name: Formatting with ruff
        run: uv run ruff format --check .

      - name: Linting with ruff
        run: uv run ruff check .

      - name: Linting with mypy
        run: uv run mypy .

      - name: unittests
        run: uv run pytest -s tests
